name: Format code

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install black
      - run: black .
      - name: Commit files
        run: |
          git config user.name formatter-bot
          git add .
          git commit -m "[bot] format code with black"
          git push origin main
