name: Format code

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Formatting the code with black
        run: |
          black --verbose .
      - name: Grant write permission to GitHub Actions bot
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git pull
          git branch --set-upstream-to=origin/main main
          git branch --verbose
          git remote set-url origin "https://github-actions-bot:${{ secrets.ACCESS_TOKEN }}@github.com/aldosalasrdz/proyectos-ingenieria-software.git"
          git push origin main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: format code"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
